# Generated by Django 3.0.5 on 2020-05-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
