# Generated by Django 3.0.5 on 2020-05-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
