# Generated by Django 3.0.5 on 2020-04-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='conten',
            new_name='content',
        ),
    ]
