# Generated by Django 3.0.5 on 2020-04-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.CharField(default='no category', max_length=50),
        ),
    ]
